### ISSUE TITLE
Strings inside if are broken

### ISSUE THREAD

**Issue by AndrewSav** [Adriandmen/05AB1E#52]
Inside `if` this line: https://github.com/Adriandmen/05AB1E/blob/master/05AB1E.py#L748
put the parser into string mode. It does not put in string mode on these commands: `‘’“”`
as a result if you have “€ƒ“ inside an `if` ƒ will increment `amount_brackets` which will cause `else` to extend to the *next* bracket, which is wrong, since in this case ƒ is not a command but a literal.

**Comment by Adriandmen** [comment]
Ah, nice catch! I'll fix this in the next release.

**Comment by AndrewSav** [comment]
@Adriandmen  I'm sorry for piling it up to the same issue, but for these two I'm not sure if those are bugs are not, so just to get you to have a quick look:

1) https://github.com/Adriandmen/05AB1E/blob/master/05AB1E.py#L3036 Do you think this is correct or should it be `a -= 1` instead of `a += 1`?

2)https://github.com/Adriandmen/05AB1E/blob/master/05AB1E.py#L3723 Here  temp_list is not assigned back to global_array. Is this right?

**Comment by AndrewSav** [comment]
And a couple of support questions. 

1)Why `+` does not work on strings? The best way to concatenates strings that I found was to use string interpolation, but it's quite verbose.
2)What is the best way to get a sub-string from a string? like a[b:c]?

**Comment by Adriandmen** [comment]
Hi, to answer your question:

1. That is an error in the documentation, it should be `counter_variable += 1` instead of `-=`.
2. You are right about the global_array, that will be fixed in the next release.
3. Right now, there is no built-in for getting a substring like `a[b:c]`. There only is `£`, which gives you the substring `a[:b]`.
4. The shortest way I could find for checking if an item is a float is `DÞQ`. There is no built-in for this.

**Comment by AndrewSav** [comment]
@Adriandmen thanks, I'd suggest adding fixing the doco about `a += 1` to the to do list as well. Thank you again for your help.

**Comment by Adriandmen** [comment]
Fixed in the latest commit: https://github.com/Adriandmen/05AB1E/commit/5e7ffd748e8597bbe45ecf9f34f06efa069f2a3d
